[package]
name = "mewvoice-desktop"
version = "0.2.3"
description = "MewVoice - Voice Pack Manager for Mewgenics"
authors = ["MewVoice"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mewvoice_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
zip = "2"
uuid = { version = "1", features = ["v4"] }
tauri-plugin-updater = "2.10.0"
tauri-plugin-process = "2.3.1"
